baseURL: "https://rlskoeser.github.io/recipe-box/"
#RelativeURLs: true
CanonifyURLs: true
languageCode: "en-us"
title: "Recipe Box"
theme: "gochowdown"

menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    # - name: Cuisine
    #   weight: 3
    #   url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags

params:
  custom_css:
    - "fonts/kashanscript/stylesheet.css"
    - "css/local.css"

